"""first version db

Revision ID: d75436453c95
Revises: 
Create Date: 2019-07-04 23:56:14.053400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75436453c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('couple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_first_name', sa.String(length=30), nullable=False),
    sa.Column('p1_surname', sa.String(length=100), nullable=False),
    sa.Column('p2_first_name', sa.String(length=30), nullable=False),
    sa.Column('p2_surname', sa.String(length=100), nullable=False),
    sa.Column('mail_street_address_1', sa.String(length=100), nullable=True),
    sa.Column('mail_street_address_2', sa.String(length=100), nullable=True),
    sa.Column('mail_city', sa.String(length=100), nullable=True),
    sa.Column('mail_state_province', sa.String(length=100), nullable=True),
    sa.Column('mail_country', sa.String(length=100), nullable=False),
    sa.Column('mail_postal_code', sa.String(length=30), nullable=False),
    sa.Column('email_p1', sa.String(length=120), nullable=True),
    sa.Column('email_p2', sa.String(length=120), nullable=True),
    sa.Column('telephone_number', sa.String(length=120), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['authuser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_p1'),
    sa.UniqueConstraint('email_p2'),
    sa.UniqueConstraint('telephone_number')
    )
    op.create_table('weddingpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_package', sa.String(length=60), nullable=False),
    sa.Column('wedding_package_desc', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['authuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weddingpackage')
    op.drop_table('couple')
    op.drop_table('authuser')
    # ### end Alembic commands ###
